version: '3.8'
services:
  php:
    image: php:8.1-cli-alpine
    volumes:
      - ./:/var/pgda
    working_dir: /var/pdga

  composer:
    command: -V
    image: composer:2.4
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga
