services:
  php:
    image: 'pdga-php-data-objects-php'
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga

  composer:
    command: -V
    image: composer:2.4
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga
