name: Run PHPUnit

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install composer dependencies
      - name: Install Composer Dependencies
        run: ./bin/composer install

      # Run tests
      - name: Run Unit Tests
        run: ./bin/phpunit
